### ISSUE TITLE
Odin loves <br>

### ISSUE THREAD

**Issue by alwild** [Kaylee-Wild/odin-recipes#1]
So many `<br>'s`  I'm sure they haven't introduced styles and CSS yet.  Hopefully soon.  On the potato recipe, something like
`<ol style="line-height: 45px">`  Would give you the same spacing instead of having a `<br>` between each line.

**Comment by Kaylee-Wild** [comment]
They didn't teach me the <br> I just googled it because I wanted more line
space lol. Thanks for the line height info though I'll need to get that
changed today

Css is after this recipes project 😄
